// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Data;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260423001708_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("WebAPI.Tables.Hobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Outdoor",
                            Description = "Scaling natural and artificial rock faces",
                            Name = "Rock Climbing"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Creative",
                            Description = "Acrylic and watercolor painting",
                            Name = "Painting"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Strategy",
                            Description = "Competitive and casual chess play",
                            Name = "Chess"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Outdoor",
                            Description = "Trail hiking and backpacking",
                            Name = "Hiking"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Music",
                            Description = "Acoustic and electric guitar",
                            Name = "Guitar"
                        });
                });

            modelBuilder.Entity("WebAPI.Tables.StudentInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CollegeProgram")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FavoriteElectiveCourse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FavoriteMajorCourse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YearInProgram")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StudentInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CollegeProgram = "Information Technology",
                            FavoriteElectiveCourse = "Digital Photography",
                            FavoriteMajorCourse = "Web Development",
                            FullName = "Jane Doe",
                            Instructor = "Dr. Smith",
                            YearInProgram = "Junior"
                        },
                        new
                        {
                            Id = 2,
                            CollegeProgram = "Computer Science",
                            FavoriteElectiveCourse = "Music Theory",
                            FavoriteMajorCourse = "Data Structures",
                            FullName = "John Smith",
                            Instructor = "Dr. Jones",
                            YearInProgram = "Sophomore"
                        },
                        new
                        {
                            Id = 3,
                            CollegeProgram = "Cybersecurity",
                            FavoriteElectiveCourse = "Art History",
                            FavoriteMajorCourse = "Network Security",
                            FullName = "Maria Garcia",
                            Instructor = "Prof. Lee",
                            YearInProgram = "Freshman"
                        },
                        new
                        {
                            Id = 4,
                            CollegeProgram = "Software Engineering",
                            FavoriteElectiveCourse = "Philosophy",
                            FavoriteMajorCourse = "System Design",
                            FullName = "Alex Johnson",
                            Instructor = "Dr. Patel",
                            YearInProgram = "Senior"
                        },
                        new
                        {
                            Id = 5,
                            CollegeProgram = "Information Technology",
                            FavoriteElectiveCourse = "Psychology",
                            FavoriteMajorCourse = "Database Systems",
                            FullName = "Sam Williams",
                            Instructor = "Dr. Smith",
                            YearInProgram = "Junior"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
